# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BDfrUD5E4KpNseqS8YyIXlyd26eYyIzb
"""



import nltk
import string
#from nltk.tokenize import  word_tokenize,sent_tokenize
#from nltk.tokenize import  WordPunctTokenizer
#from nltk.corpus import stopwords
#from nltk.stem import PorterStemmer,WordNetLemmatizer
#from nltk import pos_tag
nltk.download('punkt')
nltk.download('averaged_perceptron_tagger')
nltk.download('wordnet')
nltk.download('stopwords')



def preprocess(text):
  #first tokenization
    text = text.lower()

    sents = sent_tokenize(text)
    print("The number of sentences is", len(sents))

    text_p = "".join([char for char in text if char not in string.punctuation])
    
    words = word_tokenize(text_p)
    print("The number of tokens is", len(words))

    average_tokens = round(len(words)/len(sents))
    print("The average number of tokens per sentence is",average_tokens)

    unique_tokens = set(words)
    print("The number of unique tokens are", len(unique_tokens))
    
    
    stop_words = stopwords.words('english')
    filtered_words = [word for word in words if word not in stop_words]
    print("The number of total tokens after removing stopwords are", len((filtered_words)))
    
    porter = PorterStemmer()
    stemmed = [porter.stem(word) for word in filtered_words]
    
    lemmatizer = WordNetLemmatizer()
    lemmatized = [lemmatizer.lemmatize(word) for word in filtered_words]
    
    pos = pos_tag(filtered_words)
    
    return words, filtered_words, stemmed, pos , lemmatized 

texte = """Perhaps one of the most significant advances made by Arabic mathematics began at this time with the work of al-Khwarizmi, namely the beginnings of algebra. It is important to understand just how significant this new idea was. It was a revolutionary move away from the Greek concept of mathematics which was essentially geometry. Algebra was a unifying theory which allowed rational numbers, irrational numbers, geometrical magnitudes, etc., to all be treated as "algebraic objects". It gave mathematics a whole new development path so much broader in concept to that which had existed before, and provided a vehicle for future development of the subject. Another important aspect of the introduction of algebraic ideas was that it allowed mathematics to be applied to itself in a way which had not happened before."""


words, filtered_words, stemmed, pos , lemmatized  = preprocess(texte)

print('Words:', words[:50])
print('Filtered words:', filtered_words[:50])
print('**********Stemmed words + lemms:**********')
for i in range(len(filtered_words)):
    print(filtered_words[i], stemmed[i], lemmatized[i],sep=" : ")
print('**********Part of Speech:**********')
for i in range(len(pos)):
    print(pos[i][0], "\t: ", pos[i][1])

!pip install camel-tools

